name: Arpit Deploy to ECR

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::135893829551:role/LabRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push app image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          APP_REPOSITORY: arpit-clo835-app
          APP_IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$APP_REPOSITORY:$APP_IMAGE_TAG .
          docker push $ECR_REGISTRY/$APP_REPOSITORY:$APP_IMAGE_TAG
